// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSV3JLsXRaF2AIE2ssDCegcDo-FZfaSHA',
    appId: '1:380064713396:web:576840201fe128415ba5e1',
    messagingSenderId: '380064713396',
    projectId: 'login-firebase-d53a8',
    authDomain: 'login-firebase-d53a8.firebaseapp.com',
    storageBucket: 'login-firebase-d53a8.firebasestorage.app',
    measurementId: 'G-96GPDC2RBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9of59kzIFTTH3H6xXgn8zNRGPhC_su50',
    appId: '1:380064713396:android:079bdf55642eea2d5ba5e1',
    messagingSenderId: '380064713396',
    projectId: 'login-firebase-d53a8',
    storageBucket: 'login-firebase-d53a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwUUCPnIDNA3VYGweFnxk_GLFw8XFVoew',
    appId: '1:380064713396:ios:7b47f7a1e50e1ab75ba5e1',
    messagingSenderId: '380064713396',
    projectId: 'login-firebase-d53a8',
    storageBucket: 'login-firebase-d53a8.firebasestorage.app',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwUUCPnIDNA3VYGweFnxk_GLFw8XFVoew',
    appId: '1:380064713396:ios:7b47f7a1e50e1ab75ba5e1',
    messagingSenderId: '380064713396',
    projectId: 'login-firebase-d53a8',
    storageBucket: 'login-firebase-d53a8.firebasestorage.app',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSV3JLsXRaF2AIE2ssDCegcDo-FZfaSHA',
    appId: '1:380064713396:web:1193c2c4a4bce22c5ba5e1',
    messagingSenderId: '380064713396',
    projectId: 'login-firebase-d53a8',
    authDomain: 'login-firebase-d53a8.firebaseapp.com',
    storageBucket: 'login-firebase-d53a8.firebasestorage.app',
    measurementId: 'G-GRKQ79B348',
  );
}
